server:
  port: 8080

spring:
  data:
    mongodb:
       host: localhost
       port: 27017
       database: lotto

lottozahlen-api:
  westlottoRssFeedUrl: http://www.ergebnisse.westlotto.de/gewinnzahlen/draw.rss
  autoUpdate:
    enabled: false
    cronSchedule: '0 * * * * *'

