server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

lottozahlen-api:
  westlottoRssFeedUrl: http://www.ergebnisse.westlotto.de/gewinnzahlen/lottozahlen.rss

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG